name: Daily Bible Verse

on:
  schedule:
    - cron: '0 22 * * *'   # 6AM Philippine time
    - cron: '0 1 * * *'    # 9AM Philippine time
    - cron: '0 4 * * *'    # 12NN Philippine time
    - cron: '0 7 * * *'    # 3PM Philippine time
    - cron: '0 10 * * *'   # 6PM Philippine time
    - cron: '0 13 * * *'   # 9PM Philippine time
  workflow_dispatch:       # allows manual trigger

jobs:
  send-verse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests python-dotenv

      - name: Send Bible Verse Email
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python bible_email.py